server.port=${PORT:3001}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auction}
spring.datasource.username=${DB_USER:auction}
spring.datasource.password=${DB_PASSWORD:auction}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
