apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/akashnixon/auction-frontend:deployment
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: auction-config
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: auction
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
