apiVersion: v1
kind: Secret
metadata:
  name: auction-secrets
  namespace: auction
type: Opaque
stringData:
  DB_USER: auction
  DB_PASSWORD: auction
  JWT_SECRET: dev_secret_change_me_please_update
  POSTGRES_DB: auction
  POSTGRES_USER: auction
  POSTGRES_PASSWORD: auction
