server.port=${PORT:3003}

services.user.base-url=${USER_SERVICE_BASE_URL:http://localhost:3001}
services.bid.base-url=${BID_SERVICE_BASE_URL:http://localhost:3004}
services.notification.base-url=${NOTIFICATION_SERVICE_BASE_URL:http://localhost:3005}

auction.scheduler.enabled=${AUCTION_SCHEDULER_ENABLED:true}
auction.scheduler.leader=${AUCTION_SCHEDULER_LEADER:true}
